### ISSUE TITLE
yarn run-mock not working as expected

### ISSUE THREAD

**Issue by kayrules** [fbsamples/fbinstant-samples#10]
The command not replacing the production js with the mock js script. To fix this, you need to enter the task-name in the html file as below:

```
<!-- build:js -->
<script src="https://connect.facebook.net/en_US/fbinstant.6.2.js"></script>
<!-- endbuild -->
```

so it will replace that block properly into this:
```
<script src="js/mock/fbinstant.6.2.mock.js"></script>
```

**Comment by mingcaocao** [comment]
This is a good callout. I don't find a better way to automatically deal with this though. Any ideas?

**Comment by mingcaocao** [comment]
Issue fixed in the newest pull request.
