### ISSUE TITLE
Problem when running hello-world project

### ISSUE THREAD

**Issue by PhanVanLinh** [fbsamples/fbinstant-samples#12]
I have a problem with run hello-world project
After config project and run
`yarn run-mock --project hello-world`, my screen only display

![Screen Shot 2019-04-17 at 12](https://user-images.githubusercontent.com/15084259/56264477-2a1b0000-6119-11e9-801a-b8b02f0af026.png)

If I run, `yarn run-dist --project hello-world`. It open `embedded player` browser correctly

I am using Mac Sierra 10.12.6 with node version (`v11.10.1`) and Chrome browser. 
Any help or suggestion would be great appreciated.

**Comment by mingcaocao** [comment]
This is because you cannot fetch user information in the mock mode.
