### ISSUE TITLE
Running scripts is not working with latest version of Node

### ISSUE THREAD

**Issue by Jovan27** [fbsamples/fbinstant-samples#13]
I was getting this error when running scripts until I downgraded from node-v10.15.3 to node-v8.16.0

> PS C:\Users\Yo\Desktop\fbinstant-samples-master> yarn run-mock --project hello-world
yarn run v1.15.2
$ gulp run-mock --project hello-world
gulp run-mock --project hello-world[10808]: c:\ws\src\node_contextify.cc:626: Assertion `args[1]->IsString()' failed.
 1: 00007FF7E62FF04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF7E62DA0C6 node::MakeCallback+4518
 3: 00007FF7E62DA17F node::MakeCallback+4703
 4: 00007FF7E62AF630 node::DecodeWrite+13024
 5: 00007FF7E6ADC122 v8::internal::OptimizingCompileDispatcher::Unblock+59890
 6: 00007FF7E6ADD289 v8::internal::OptimizingCompileDispatcher::Unblock+64345
 7: 00007FF7E6ADC5CC v8::internal::OptimizingCompileDispatcher::Unblock+61084
 8: 00007FF7E6ADC4EB v8::internal::OptimizingCompileDispatcher::Unblock+60859
 9: 000001585CBDC5C1
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mingcaocao** [comment]
This is a known issue for gulp 3. Current plan is to upgrade the project to gulp 4 and see if it will fix the problem. That includes some gulp file change so it is gonna take some time.

**Comment by mingcaocao** [comment]
Upgrade the gulp from 3 to 4. It should be fixed now.
