### ISSUE TITLE
keep showing 0% loaded

### ISSUE THREAD

**Issue by LabN36** [fbsamples/fbinstant-samples#26]
Hi,

I'm not sure what going wrong, the basic sample app keep showing loading screen.

it's neither working on local nor in production.

I've tried adding `console.log` at different place and it seems the script is not coming inside `FBInstant.initializeAsync().then` I'm not sure why.

i use command `yarn upload --project hello-world` to upload the hello-world code zip file.

I'm attaching more details here please help me what's wrong I'm doing.

[This is zip of codebase 1ce706e0-f4fc-11ea-80c6-b160fcafe6a2.zip](https://github.com/fbsamples/fbinstant-samples/files/5212744/1ce706e0-f4fc-11ea-80c6-b160fcafe6a2.zip)

**This is index.html content**
https://gist.github.com/LabN36/eaf0b95ef17f7a2216d5869740fea142

<img width="1440" alt="Screenshot 2020-09-12 at 7 02 19 PM" src="https://user-images.githubusercontent.com/10628287/92996755-a2167100-f52b-11ea-80c1-5fd476860e40.png">
<img width="1440" alt="Screenshot 2020-09-12 at 7 02 37 PM" src="https://user-images.githubusercontent.com/10628287/92996762-a93d7f00-f52b-11ea-978f-6c2999b52ecd.png">
<img width="1440" alt="Screenshot 2020-09-12 at 7 11 26 PM" src="https://user-images.githubusercontent.com/10628287/92996782-c7a37a80-f52b-11ea-8a79-b5d3f7d519c1.png">

**Comment by Noel-FB** [comment]
@LabN36 I believe this issue is solved now. More info here: https://www.facebook.com/groups/instantgamedevelopers/permalink/1415940765268745/
