### ISSUE TITLE
setLoadingProgress not working

### ISSUE THREAD

**Issue by cheasamnang** [fbsamples/fbinstant-samples#4]
FBInstant.setLoadingProgress not show loading process

**Comment by mingcaocao** [comment]
@cheasamnang Thank you for reporting the issue. Investigating now.

**Comment by mingcaocao** [comment]
@cheasamnang My observation is if you run the samples on local host, it loads so fast so you won't be able to see the loading process loading. But if you upload the samples to the www.developer.facebook.com, then testing the app from there, you will find the loading process actually happens. Closed the issue, but feel free to reopen it if you think this is not the case for you.
